services:
  postgres:
    image: postgres:15.14-alpine3.22
    container_name: basic_fasapi_postgres
    environment:
      POSTGRES_DB: basic_fasapi_db
      POSTGRES_USER: fasapi_user
      POSTGRES_PASSWORD: fasapi_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  postgres_data:
    driver: local
